baseURL = "https://splvm.github.io/virtsys-meetup/"
languageCode = "en-us"
title = "Virtsys Meetup"
theme ="hugo-fresh"
googleAnalytics = "UA-83991908-1"
disableHugoGeneratorInject = true

[markup]
  [markup.highlight]
    style = "tomorrow-night"


[params]


[params.font]
  name = "Nunito Sans"
  sizes = [
    400.0,
    800.0
  ]

  [params.section2]
  title = "Annoucements"
  
  [[params.section2.features]]
    title = "Jan 15, 2024"
    text = "Thanks for visiting SPLVM **Virtualized System Meetup**. We will follow UCSD CSE291 on Virtualization. Please check our schedule join us if you are interested. The meetup will be held every Monday at 5:00pm PST. The first meetup will be on January 22, 2021. Please contact us if you want to present a paper or give a guest talk. "
    
  # [[params.section2.features]]
  #   title = "something"
  #   text = "Thanks for visiting SPLVM 'Vitual System Meetup'. We will follow UCSD CSE291 on Virtualization. Please check our schedule below and join us if you are interested. The meetup will be held every Monday at 5:00pm PST. The first meetup will be on January 22, 2021. Please contact us if you want to present a paper or give a guest talk. "
  
  [params.hero]
  title = "Virtualized System Meetup"
  subtitle = "A virtual meetup for people interested in containers and Kubernetes"
  buttontext = "Schedule"
  buttonLink = "/virtsys-meetup/schedule"
  image = "3.png"

  # [[params.navbarLogo]]
  # image = "plug-cloud.svg"
  # link = "/virtsys-meetup"

  [[params.navbar]]
  title = "About"
  url = "/virtsys-meetup/about"

  [[params.navbar]]
  title = "Schedule"
  url = "/virtsys-meetup/schedule"

  [params.navbarLogo]
  image = "3.svg"
  link = "https://github.com/splvm"